# Generated by Django 5.0.4 on 2025-12-10 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomedicaldata",
            name="in_buffer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="biomedicaldata",
            name="temperature",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gpsdata",
            name="in_buffer",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="biomedicaldata",
            name="userid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biomedical_data",
                to="api.users",
            ),
        ),
        migrations.AlterField(
            model_name="gpsdata",
            name="userid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gps_data",
                to="api.users",
            ),
        ),
    ]
